### ISSUE TITLE
Where can we find this premium plugin please ?

### ISSUE THREAD

**Issue by chrisvidal** [responsiv/subscribe-plugin#1]
Where can we find this premium plugin please ?
I can't find it on the octobercms plugin repository:
http://octobercms.com/plugins/search?search=subscribe

thank you

**Comment by daftspunk** [comment]
This is a big plugin that is taking months to build, it may take many more (we hope not!). Thanks for your patience, it should be worth it.

**Comment by daftspunk** [comment]
Just FYI - it's open source now, but not complete.

**Comment by chrisvidal** [comment]
thanks @daftspunk 
Looking at the code, and I wonder how the scheduling of the worker is done (probably not coded yet?)
