### ISSUE TITLE
Plugin not on marketplace?

### ISSUE THREAD

**Issue by security-companion** [responsiv/subscribe-plugin#2]
Hi,
I'm interested in using your plugin and I'm asking myself why it is not listed on the octoberCMS marketplace. Is there some reason for this?
Thanks in advance
joejoe2010

**Comment by daftspunk** [comment]
This plugin is a work in progress (not finished). The content was made open source as it may be useful for learning purposes. Hope this helps!

**Comment by security-companion** [comment]
thanks for your answer and all the work you put into the plugin.

**Comment by security-companion** [comment]
Just one more question: You mention that the plugin is "not finished". What do you mean by that? Just some fine tuning or are there any major code parts still missing? (scheduling of the worker), see question at the end of issue 1

**Comment by daftspunk** [comment]
I'd say it's about 80% the way there. It just needs fine tuning and testing across all the many usage scenarios. The accompanying "sparky-theme" needs to be completed also: https://github.com/responsiv/sparky-theme

**Comment by security-companion** [comment]
okay, I see. So can I use this plugin with another theme or only with the sparky-theme?

I would like to suggest anyhow that you put the subscribe-plugin on the market although it's not finished yet because there's only one other plugin called Plans doing subscriptions but it depends on another plugin that is not available any more. You could eg. add to the documentation "this plugin is work in progress and not finished" like I've seen other developers doing.
