### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by security-companion** [responsiv/subscribe-plugin#3]
Hi daftspunk,
I'm thinking about using/adapting your plugin but there is no license specified on this repo? Could you add one because otherwise it will be difficult for people to use your plugin the correct way.

**Comment by daftspunk** [comment]
Thanks for pointing this out. MIT license has been added in 5dce6a82b71755990769461724dfa5886d180162

Enjoy!

**Comment by security-companion** [comment]
Thanks a lot!
